### ISSUE TITLE
Search in Latin alphabet in Japan map does not return anything

### ISSUE THREAD

**Issue by ghost** [fransschreuder/libosmscout#20]
I will be travel in Japan for a short time soon and I was planning to use OSMScout to get around there.

Unfortunately I went into the problem in the title.

All the addresses that my contacts gave me are transliterated and written in the Latin alphabet.
Looking for them in OSMScout does not return any output, as apparently all the names in the maps are written in local characters or ideograms.
On the other hand, it would be impossible to search in Japanese, because Japanese is not supported on the phone (yet?) - and I do not really know how to write it, even on the computer.

I do not know where the problem is here (in OSM, in the map, in the search, in the way the app processes the downloaded map), but it is pretty annoying.

PS: The preinstalled application HERE Maps find the places I am looking for.

**Comment by Theodin** [comment]
Could you try and find your addresses here: https://www.openstreetmap.org ?
If you dont, they likely arent in openstreetmap so there is no chance you'll find them in OSMScout. Or maybe they are there,. but with a different transliteration so you'd have to know where it is and see if for example the road is spelt differently.

**Comment by ghost** [comment]
EDIT: I'd say no. It is not found, so the problem is within OSM, not the application.

Sorry for writing here before investigating further! :smile:

**Comment by fransschreuder** [comment]
If you know to find the location on the map, you don't need to search. You can press and hold, then choose "navigate here"

**Comment by fransschreuder** [comment]
If it's not an app problem, I will close the issue...

**Comment by ghost** [comment]
Yes, please.

Thanks for the great work and support! :)

**Comment by fransschreuder** [comment]
:) You're welcome!

**Comment by Leon083** [comment]
Sorry if i reopen this issue, but i have a similar problem: i downloaded the japan map, but if i try to search in the search bar for example "tokyo",no results is found; if i try to search "tokyo" on openstreetmap it give a result (clearly the city of tokyo).. 
In another navigator application there was the possibility to change the visualization of the name displayed on the map: original language of the country or in another language (english better, because is the most used on openstreetmap, also for asiatic country).. It's possible to make a similar options?

P.S. By the way, it's a very good app, good work.. Thanks!

**Comment by fransschreuder** [comment]
I have no experience with special character encodings, I would very much appreciate if somebody else could join development of this app. 
Openstreetmap has a completely different search algorithm, only the map data is coming from openstreetmap
