### ISSUE TITLE
No maps available

### ISSUE THREAD

**Issue by Julmuzy** [fransschreuder/libosmscout#45]
I've recently downloaded another map and found that OSMscout cannot find any maps at all. When I restart the application it reports "no maps available" and will not allow me to do anything else. It's the supported version. Any ideas on how to resolve the situation?

**Comment by fransschreuder** [comment]
Dear Julmuzy,

Do you have the same problem with the normal version? The code should be
identical, only it has it's own set of configuration files.
Could you remove all configuration files
(~/.config/fransschreuder-osmscout, ~.local/share/fransschreuder-osmscout)

I must say that I didn't have time the last two months to look at the
application, I will try and see whether the Ubuntu updates messed something
up so that it doesn't work anymore.

Kind regards,

Frans Schreuder

2016-02-14 14:22 GMT+01:00 Julmuzy notifications@github.com:

**Comment by Julmuzy** [comment]
Hello Frans

I do not have the free version. My config files are stored in ~/.config/osmscout-support.fransschreuder, ~.local/share/osmscout-support.fransschreuder. Should I delete these ?
Kind regards

Julian

**Comment by fransschreuder** [comment]
Yes, please delete them.

2016-02-14 16:16 GMT+01:00 Julmuzy notifications@github.com:

**Comment by Julmuzy** [comment]
Hello Frans,
That appears to have worked except I had to delete the configuration files again once I downloaded another map. 
FYI other software, such as File Manager crashes as well as trying to use the 'About this phone' (to set Developer Mode) in System Settings. Both crash since the last system update. I don't know if these issues are related.
Thank you for your prompt help
Kind regards

Julian

**Comment by fransschreuder** [comment]
Thanks i will check for myself.
Op 14 feb. 2016 19:46 schreef "Julmuzy" notifications@github.com:
